# Generated by Django 3.2.23 on 2023-12-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dq4dnlzta/image/upload/v1700822700/media/images/default_profile_pz46wh.jpg', upload_to='images/'),
        ),
    ]
